modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/Sarinsa/QuickCure/issues"

[[mods]]
    modId="quick_cure"
    version="${file.jarVersion}"
    displayName="Quick Cure"
    logoFile="logo.png"
    credits="AmberGoop (Mod concept), Frenderman (Logo texture)"
    authors="Sarinsa"
    description="Makes curing zombie villagers happen instantaneously."

[[dependencies.quick_cure]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quick_cure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"
